language: node_js
node_js:
  - 18

install:
  - nvm install 18.15.0

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
